server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/finalMicroservicios
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true


message: hello from serie-service

queue:
  serie:
    name: SerieQueue

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: serie-service
    description: Info del servicio Serie
    version: 1.0.0

#config eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #solo config para los clientes de eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
