server:
  port: 8083

spring:
  application:
    name: serie-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: db_series
      port: 27017
      host: mongodb

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#Actuator: Monitoreando la salud de nuestros microservicios
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
